import collections

de = collections.deque([1, 2, 3])
de.append(4)
print("deque after append")
print(de)
de.appendleft(0)
print("deque after appendleft")
print(de)
de.pop()
print("deque after pop")
print(de)
de.popleft()
print("deque after pop left")
print(de)
print(de.index(2, 0, len(de)))  # index(ele, beg, end)
de2 = collections.deque([1, 2, 5, 2, 4, 6, 7, 1, 4])
print(de2.index(2, 2, 5))
de2.insert(2, 1)
print("de2 after insert 2 at index of 1")
print(de2)
print("count of 2 in de2")
print(de2.count(2))
print("de2 after removing 4 from first occurance")
de2.remove(4)
print(de2)
